name: CI
on:
  push:
    branches: ["main", "devel"]
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: ["main", "devel"]
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'
      - '**.yaml'

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          persist-credentials: false
          go-version-file: go.mod
          cache: true
      - run: go test -v ./...

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          persist-credentials: false
          go-version-file: go.mod
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.0
